#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Source YNH helpers
. /usr/share/yunohost/helpers

backup_dir=$1

# Get app instance name
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
local_path=$(ynh_app_setting_get $app local_path)

my_ynh_backup () {
    ynh_backup $@
    echo $2 $1 >> $backup_dir/list    
}

# Copy the app files
my_ynh_backup "$local_path" "sources"

# Copy the conf files
my_ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "conf/nginx.conf"
my_ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "conf/php-fpm.conf"
my_ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "conf/php-fpm.ini"

# Save database
dbpass=$(ynh_app_setting_get "$app" mysqlpwd)
mysqldump -u "$app" -p"$dbpass" --no-create-db "$app" > ./dump.sql
