#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

prefix=lime_
ynh_app_setting_set --app=$app --key=prefix --value=$prefix

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=1

ynh_add_fpm_config

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Creating a data directory..." --weight=1

# Remove upload if empty
rmdir $data_dir 2> /dev/null && mv "$install_dir/upload" $data_dir || true
chmod -R o-rwx "$data_dir"
chown -R $app:www-data "$data_dir"
ln -s $data_dir/upload $install_dir/upload 2> /dev/null || true

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="../conf/config.php" --destination="$install_dir/application/config/config.php"

chmod 400 "$install_dir/application/config/config.php"
chown $app:$app "$install_dir/application/config/config.php"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression --message="Installing app..."

ls_cli=$install_dir/application/commands/console.php

fullname=$(ynh_user_get_info --username="$admin" --key="fullname")
mail=$(ynh_user_get_info --username="$admin" --key="mail")

# Permission should be correctly set before to do this
ynh_exec_as "$app" php$phpversion $ls_cli install "$admin" "$password" "$fullname" "$mail"

# Permission should be correctly set before to do this
#ynh_exec_as "$app" php$phpversion $ls_cli install "$admin" "$(ynh_string_random 24)" "$fullname" "$mail"

#=================================================
# LOAD SQL SPECIFIC CONFIG
#=================================================
ynh_script_progression --message="Loading SQL specific config..."

ynh_add_config --template="../conf/data.sql" --destination="./data.sql"

ynh_mysql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./data.sql

ynh_secure_remove --file=./data.sql

#=================================================
# ADD NICE THEMES
#=================================================
#ynh_script_progression --message="Adding nice themes..."

#ynh_setup_source "$data_dir/upload/templates/libreform" libreform
#ynh_setup_source "$install_dir/upload/templates/librepoll" librepoll

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP SSOWAT
#=================================================

# Grant $admin access to /admin, whether or not Visitors has been selected in the installation form
ynh_permission_update --permission="admin" --add="$admin"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
