#!/bin/bash

app="limesurvey"

# Retrieve arguments
domain=$1
path=$2
admin=$3
language=$4

# Check if admin exists
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
    echo "Wrong admin"
    exit 1
fi
sudo yunohost app setting $app admin -v $admin
sudo yunohost app setting $app language -v $language

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'opensondage' as database name and user
db_user=$app

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Copy files to the right place
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path


# Db installation
mysql -u $db_user -p$db_pwd $db_user < ../sources/installer/sql/create-mysql.sql
sudo sed -i "s/yunoadmin/$admin/g" ../conf/mysql_data.sql
mysql -u $db_user -p$db_pwd $db_user < ../conf/mysql_data.sql


sudo cp ../conf/config.php.template $final_path/application/config/config.php

sudo sed -i "s/yunouser/$db_user/g" $final_path/application/config/config.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/application/config/config.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/application/config/config.php

for user in $(sudo yunohost user list | grep '^  [^ ]*:' | sed -e "s/^  \([^ ]*\):/\1/g")
do
    if [ $user != $admin ];
        then
            mysql -u $db_user -p$db_pwd $db_user -e "INSERT INTO prefix_users (users_name) VALUES ('$user');INSERT INTO prefix_permissions (entity,entity_id,uid,permission,create_p,read_p,update_p,delete_p,import_p,export_p) SELECT 'global',0,uid,'surveys',1,1,1,1,0,1 FROM prefix_users WHERE users_name='$user'"

        fi
done

# Set permissions
sudo chown -R www-data: $final_path
sudo chmod u+w $final_path/tmp
sudo chmod u+w $final_path/upload
sudo chmod u+w $final_path/application/config/

sudo yunohost app addaccess $app -u $admin

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting $app skipped_uris -v "/"  
#sudo yunohost app setting $app protected_uris -v "/index.php?r=admin,/index.php?r=plugins,/scripts"
sudo yunohost app ssowatconf

