#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Database prefix
prefix=lime_
ynh_app_setting_set --key=prefix --value="$prefix"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

# Move upload directory to data_dir, with a symlink
if [ -d "$data_dir/upload" ]; then
    ynh_print_warn "An upload directory already exist, reusing it."
else
    mv "$install_dir/upload" "$data_dir"
fi

ln -s "$data_dir/upload" "$install_dir/upload"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
chown -R "$app:www-data" "$data_dir/upload"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/application/config/config.php"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/application/config/config.php"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown "$app:$app" "$install_dir/application/config/config.php"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

ls_cli="$install_dir/application/commands/console.php"

fullname=$(ynh_user_get_info --username="$admin" --key="fullname")
mail=$(ynh_user_get_info --username="$admin" --key="mail")

# Permission should be correctly set before to do this
ynh_exec_as_app "php$php_version" "$ls_cli" install "$admin" "$password" "$fullname" "$mail"

#=================================================
# LOAD SQL SPECIFIC CONFIG
#=================================================
ynh_script_progression "Loading SQL specific config..."

ynh_config_add --template="data.sql" --destination="./data.sql"

ynh_mysql_db_shell < ./data.sql

ynh_safe_rm ./data.sql

#=================================================
# ADD NICE THEMES
#=================================================
#ynh_script_progression "Adding nice themes..."

#ynh_setup_source "$data_dir/upload/templates/libreform" libreform
#ynh_setup_source "$install_dir/upload/templates/librepoll" librepoll

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated PHP-FPM config
ynh_config_add_phpfpm

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
